### ISSUE TITLE
Error when using addFieldGroupToSchema

### ISSUE THREAD

**Issue by mdonke** [adobe/aepp#18]
### Expected Behaviour
addFieldGroupToSchema works

### Actual Behaviour
error:
```
  File "/home/xxx/.local/lib/python3.9/site-packages/aepp/schema.py", line 694, in addFieldGroupToSchema
    res = self.putSchema(schemaDef)
  File "/home/xxx/.local/lib/python3.9/site-packages/aepp/schema.py", line 476, in putSchema
    if schemaId.startswith("https://"):
AttributeError: 'dict' object has no attribute 'startswith'
```
### Reproduce Scenario (including but not limited to)

my sample code:
`res = target_instance.addFieldGroupToSchema(schemaId=existing_schema_id, fieldGroupIds=new_field_group_ids)`

#### Platform and Version
Linux/Latest

Issue may be in 

https://github.com/adobe/aepp/blob/main/aepp/schema.py#L694

Maybe an easy fix would be to use 

`res = self.putSchema(schemaId=schemaId, schemaDef=schemaDef)`

instead?

**Comment by pitchmuc** [comment]
Hello @mdonke 
Are you passing the fieldGroupId as a list of string with the strng being the ids of the fields groups ?

**Comment by pitchmuc** [comment]
Thanks! 
I found the issue was on me :( 
I abstracted the PUT method for schema but I missed to pass the schema Id calling the method and just passed the new definition. 
I just did the change 
`res = self.putSchema(schemaDef)`
became
`res = self.putSchema(schemaId,schemaDef)`

The latest commit should fix it. 
A new release is planned soon.

**Comment by mdonke** [comment]
Nice! Thanks. I'll wait for the release, update my aepp lib and will test and report back!

**Comment by mdonke** [comment]
Tested successfully. Thanks for fixing it.
